### PR TITLE
Radio online

### PR DESCRIPTION
**Pull request by snowy-shadow**
Still a little funky

### CODE REVIEW

**Comment by frroossst** [comment]
This is a big pull, I will have to manually merge things in. I assume all the relevant code was added to CPP_flight_computer_program or is it in AvionicsRX? @snowy-shadow

**Comment by snowy-shadow** [comment]
- I did the dev in AvionicsRX and copied it over to CPP_flight, so those changes should be identical. ]
- There might be some library change because I re downloaded the lib because it broke one day.
- code actions now uses cache instead of redownloading everything from scratch for everyrun (I merged it with your current action, shouldn't change anything you can double check)

**Comment by snowy-shadow** [comment]
I can show you around on saturday

**Comment by frroossst** [comment]
Also, we shouldn't merge in AvionicsRX if it is not needed, and yes we'll merge on Saturday in person

**Comment by snowy-shadow** [comment]
the RX is meant for the ground station, but if we are using a different radio and a different lib for the ground station then we can delete it

Yes, I already resolved the merge conflicts

**Comment by frroossst** [comment]
Your pio build is failing, check if you can compile the entire project on local

**Pull request closed without merging**
